using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Domain.Concrete
{
    public class CinemaInitializer : System.Data.Entity.DropCreateDatabaseAlways<EFDbContext>
    {
        protected override void Seed(EFDbContext context)
        {
            //    SEQUENCE:
            //
            //    1. location, 
            //    2. movie 
            //    3. roomlayout
            //    4. room 
            //    5. seat 
            //    6. show
            //    7. ticket

            /* -----------start of table creation------------ */
            var locations = new List<Location>
            {
            new Location{Name="Cinema Breda",City="Breda", Rooms=6,TicketPrice=10.00M},
            new Location{Name="Cinema Eindhoven",City="Eindhoven", Rooms=6,TicketPrice=10.00M},
            new Location{Name="Cinema Rotterdam",City="Rotterdam", Rooms=6,TicketPrice=10.00M}
            };

            locations.ForEach(s => context.Locations.Add(s));
            context.SaveChanges();
            /* -----------end of table creation------------ */

            /* -----------start of table creation------------ */
            var movies = new List<Movie>
            {
            new Movie{Name="Darkest Hour",Language="Engels",LanguageSub="Nederlands", Age=16,MovieType=2,Length=120,Is3D=false,LocationID=1},
            new Movie{Name="Red Sparrow",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=140,Is3D=false,LocationID=1},
            new Movie{Name="Death Wish",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=108,Is3D=true,LocationID=1},
            new Movie{Name="Diep in de Zee",Language="Nederlands",LanguageSub="Nederlands",Age=6,MovieType=2,Length=91,Is3D=false,LocationID=1},
            new Movie{Name="Black Panther",Language="Engels",LanguageSub="Nederlands",Age=12,MovieType=2,Length=134,Is3D=true,LocationID=1},
            new Movie{Name="Bankier van het Verzet",Language="Nederlands",LanguageSub="Nederlands",Age=12,MovieType=2,Length=123,Is3D=false,LocationID=1},
            new Movie{Name="The Shape of Water",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=123,Is3D=false,LocationID=1},
            new Movie{Name="Three BillBoards Outside Ebbing, Missouri",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=115,Is3D=false,LocationID=1},
            new Movie{Name="Buurman en Buurman bouwen een huis",Language="Nederlands",LanguageSub="Nederlands",Age=4,MovieType=2,Length=150,Is3D=false,LocationID=1},

            new Movie{Name="Darkest Hour",Language="Engels",LanguageSub="Nederlands", Age=16,MovieType=2,Length=120,Is3D=false,LocationID=2},
            new Movie{Name="Tomb Raider",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=140,Is3D=false,LocationID=2},
            new Movie{Name="Death Wish",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=108,Is3D=true,LocationID=2},
            new Movie{Name="Diep in de Zee",Language="Nederlands",LanguageSub="Nederlands",Age=6,MovieType=2,Length=91,Is3D=false,LocationID=2},
            new Movie{Name="Black Panther",Language="Engels",LanguageSub="Nederlands",Age=12,MovieType=2,Length=134,Is3D=true,LocationID=2},
            new Movie{Name="Bankier van het Verzet",Language="Nederlands",LanguageSub="Nederlands",Age=12,MovieType=2,Length=123,Is3D=false,LocationID=2},
            new Movie{Name="The Shape of Water",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=123,Is3D=false,LocationID=2},
            new Movie{Name="Three BillBoards Outside Ebbing, Missouri",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=115,Is3D=false,LocationID=2},
            new Movie{Name="Buurman en Buurman bouwen een huis",Language="Nederlands",LanguageSub="Nederlands",Age=4,MovieType=2,Length=150,Is3D=false,LocationID=2},

            new Movie{Name="Darkest Hour",Language="Engels",LanguageSub="Nederlands", Age=16,MovieType=2,Length=120,Is3D=false,LocationID=3},
            new Movie{Name="Red Sparrow",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=140,Is3D=false,LocationID=3},
            new Movie{Name="Pacific Rim Uprising",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=108,Is3D=true,LocationID=3},
            new Movie{Name="Diep in de Zee",Language="Nederlands",LanguageSub="Nederlands",Age=6,MovieType=2,Length=91,Is3D=false,LocationID=3},
            new Movie{Name="Black Panther",Language="Engels",LanguageSub="Nederlands",Age=12,MovieType=2,Length=134,Is3D=true,LocationID=3},
            new Movie{Name="Bankier van het Verzet",Language="Nederlands",LanguageSub="Nederlands",Age=12,MovieType=2,Length=123,Is3D=false,LocationID=3},
            new Movie{Name="The Shape of Water",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=123,Is3D=false,LocationID=3},
            new Movie{Name="Three BillBoards Outside Ebbing, Missouri",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=115,Is3D=false,LocationID=3},
            new Movie{Name="Buurman en Buurman bouwen een huis",Language="Nederlands",LanguageSub="Nederlands",Age=4,MovieType=2,Length=150,Is3D=false,LocationID=3}

            };

            movies.ForEach(s => context.Movies.Add(s));
            context.SaveChanges();
            /* -----------end of table creation------------ */

            /* -----------start of table creation------------ */
            var rooms = new List<Room>
            {
            new Room{RoomID=1,RoomNumber=1,TotalSeats=240},
            new Room{RoomID=2,RoomNumber=2,TotalSeats=240},
            new Room{RoomID=3,RoomNumber=3,TotalSeats=240},
            new Room{RoomID=4,RoomNumber=4,TotalSeats=77},
            new Room{RoomID=5,RoomNumber=5,TotalSeats=50},
            new Room{RoomID=6,RoomNumber=6,TotalSeats=50}
            };

            rooms.ForEach(s => context.Rooms.Add(s));
            context.SaveChanges();
            /* -----------end of table creation------------ */

            /* -----------start of table creation------------*/
            var seats = new List<Seat>
            {
            new Seat{RoomID=1,RowNumber=1,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=20},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=20},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=20},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=20},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=20},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=20},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=20},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=20},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=20},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=20},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=20},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=20},
            new Seat{RoomID=4,RowNumber=1,SeatNumber=1},
            new Seat{RoomID=4,RowNumber=1,SeatNumber=2},
            new Seat{RoomID=4,RowNumber=1,SeatNumber=3},
            new Seat{RoomID=4,RowNumber=1,SeatNumber=4},
            new Seat{RoomID=4,RowNumber=1,SeatNumber=5},
            new Seat{RoomID=4,RowNumber=1,SeatNumber=6},
            new Seat{RoomID=4,RowNumber=2,SeatNumber=1},
            new Seat{RoomID=4,RowNumber=2,SeatNumber=2},
            new Seat{RoomID=4,RowNumber=2,SeatNumber=3},
            new Seat{RoomID=4,RowNumber=2,SeatNumber=4},
            new Seat{RoomID=4,RowNumber=2,SeatNumber=5},
            new Seat{RoomID=4,RowNumber=2,SeatNumber=6},
            new Seat{RoomID=4,RowNumber=3,SeatNumber=2},
            new Seat{RoomID=4,RowNumber=3,SeatNumber=3},
            new Seat{RoomID=4,RowNumber=3,SeatNumber=4},
            new Seat{RoomID=4,RowNumber=3,SeatNumber=5},
            new Seat{RoomID=4,RowNumber=3,SeatNumber=6},
            new Seat{RoomID=4,RowNumber=4,SeatNumber=1},
            new Seat{RoomID=4,RowNumber=4,SeatNumber=2},
            new Seat{RoomID=4,RowNumber=4,SeatNumber=3},
            new Seat{RoomID=4,RowNumber=4,SeatNumber=4},
            new Seat{RoomID=4,RowNumber=4,SeatNumber=5},
            new Seat{RoomID=4,RowNumber=4,SeatNumber=6},
            new Seat{RoomID=4,RowNumber=5,SeatNumber=2},
            new Seat{RoomID=4,RowNumber=5,SeatNumber=3},
            new Seat{RoomID=4,RowNumber=5,SeatNumber=4},
            new Seat{RoomID=4,RowNumber=5,SeatNumber=5},
            new Seat{RoomID=4,RowNumber=5,SeatNumber=6},
            new Seat{RoomID=4,RowNumber=6,SeatNumber=1},
            new Seat{RoomID=4,RowNumber=6,SeatNumber=2},
            new Seat{RoomID=4,RowNumber=6,SeatNumber=3},
            new Seat{RoomID=4,RowNumber=6,SeatNumber=4},
            new Seat{RoomID=4,RowNumber=6,SeatNumber=5},
            new Seat{RoomID=4,RowNumber=6,SeatNumber=6},
            new Seat{RoomID=4,RowNumber=7,SeatNumber=2},
            new Seat{RoomID=4,RowNumber=7,SeatNumber=3},
            new Seat{RoomID=4,RowNumber=7,SeatNumber=4},
            new Seat{RoomID=4,RowNumber=7,SeatNumber=5},
            new Seat{RoomID=4,RowNumber=7,SeatNumber=6},
            new Seat{RoomID=4,RowNumber=1,SeatNumber=7},
            new Seat{RoomID=4,RowNumber=1,SeatNumber=8},
            new Seat{RoomID=4,RowNumber=1,SeatNumber=9},
            new Seat{RoomID=4,RowNumber=1,SeatNumber=10},
            new Seat{RoomID=4,RowNumber=1,SeatNumber=11},
            new Seat{RoomID=4,RowNumber=2,SeatNumber=7},
            new Seat{RoomID=4,RowNumber=2,SeatNumber=8},
            new Seat{RoomID=4,RowNumber=2,SeatNumber=9},
            new Seat{RoomID=4,RowNumber=2,SeatNumber=10},
            new Seat{RoomID=4,RowNumber=2,SeatNumber=11},
            new Seat{RoomID=4,RowNumber=3,SeatNumber=8},
            new Seat{RoomID=4,RowNumber=3,SeatNumber=9},
            new Seat{RoomID=4,RowNumber=3,SeatNumber=10},
            new Seat{RoomID=4,RowNumber=3,SeatNumber=11},
            new Seat{RoomID=4,RowNumber=4,SeatNumber=7},
            new Seat{RoomID=4,RowNumber=4,SeatNumber=8},
            new Seat{RoomID=4,RowNumber=4,SeatNumber=9},
            new Seat{RoomID=4,RowNumber=4,SeatNumber=10},
            new Seat{RoomID=4,RowNumber=4,SeatNumber=11},
            new Seat{RoomID=4,RowNumber=5,SeatNumber=8},
            new Seat{RoomID=4,RowNumber=5,SeatNumber=9},
            new Seat{RoomID=4,RowNumber=5,SeatNumber=10},
            new Seat{RoomID=4,RowNumber=5,SeatNumber=11},
            new Seat{RoomID=4,RowNumber=6,SeatNumber=7},
            new Seat{RoomID=4,RowNumber=6,SeatNumber=8},
            new Seat{RoomID=4,RowNumber=6,SeatNumber=9},
            new Seat{RoomID=4,RowNumber=6,SeatNumber=10},
            new Seat{RoomID=4,RowNumber=6,SeatNumber=11},
            new Seat{RoomID=4,RowNumber=7,SeatNumber=7},
            new Seat{RoomID=4,RowNumber=7,SeatNumber=8},
            new Seat{RoomID=4,RowNumber=7,SeatNumber=9},
            new Seat{RoomID=4,RowNumber=7,SeatNumber=10},
            new Seat{RoomID=4,RowNumber=7,SeatNumber=11},
            new Seat{RoomID=5,RowNumber=1,SeatNumber=1},
            new Seat{RoomID=5,RowNumber=1,SeatNumber=2},
            new Seat{RoomID=5,RowNumber=1,SeatNumber=3},
            new Seat{RoomID=5,RowNumber=1,SeatNumber=4},
            new Seat{RoomID=5,RowNumber=1,SeatNumber=5},
            new Seat{RoomID=5,RowNumber=1,SeatNumber=6},
            new Seat{RoomID=5,RowNumber=1,SeatNumber=7},
            new Seat{RoomID=5,RowNumber=1,SeatNumber=8},
            new Seat{RoomID=5,RowNumber=1,SeatNumber=9},
            new Seat{RoomID=5,RowNumber=1,SeatNumber=10},
            new Seat{RoomID=5,RowNumber=2,SeatNumber=1},
            new Seat{RoomID=5,RowNumber=2,SeatNumber=2},
            new Seat{RoomID=5,RowNumber=2,SeatNumber=3},
            new Seat{RoomID=5,RowNumber=2,SeatNumber=4},
            new Seat{RoomID=5,RowNumber=2,SeatNumber=5},
            new Seat{RoomID=5,RowNumber=2,SeatNumber=6},
            new Seat{RoomID=5,RowNumber=2,SeatNumber=7},
            new Seat{RoomID=5,RowNumber=2,SeatNumber=8},
            new Seat{RoomID=5,RowNumber=2,SeatNumber=9},
            new Seat{RoomID=5,RowNumber=2,SeatNumber=10},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=1},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=2},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=3},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=4},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=5},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=6},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=7},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=8},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=9},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=10},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=11},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=12},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=13},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=14},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=15},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=1},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=2},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=3},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=4},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=5},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=6},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=7},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=8},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=9},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=10},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=11},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=12},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=13},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=14},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=15},
            new Seat{RoomID=6,RowNumber=1,SeatNumber=1},
            new Seat{RoomID=6,RowNumber=1,SeatNumber=2},
            new Seat{RoomID=6,RowNumber=1,SeatNumber=3},
            new Seat{RoomID=6,RowNumber=1,SeatNumber=4},
            new Seat{RoomID=6,RowNumber=1,SeatNumber=5},
            new Seat{RoomID=6,RowNumber=1,SeatNumber=6},
            new Seat{RoomID=6,RowNumber=1,SeatNumber=7},
            new Seat{RoomID=6,RowNumber=1,SeatNumber=8},
            new Seat{RoomID=6,RowNumber=1,SeatNumber=9},
            new Seat{RoomID=6,RowNumber=1,SeatNumber=10},
            new Seat{RoomID=6,RowNumber=2,SeatNumber=1},
            new Seat{RoomID=6,RowNumber=2,SeatNumber=2},
            new Seat{RoomID=6,RowNumber=2,SeatNumber=3},
            new Seat{RoomID=6,RowNumber=2,SeatNumber=4},
            new Seat{RoomID=6,RowNumber=2,SeatNumber=5},
            new Seat{RoomID=6,RowNumber=2,SeatNumber=6},
            new Seat{RoomID=6,RowNumber=2,SeatNumber=7},
            new Seat{RoomID=6,RowNumber=2,SeatNumber=8},
            new Seat{RoomID=6,RowNumber=2,SeatNumber=9},
            new Seat{RoomID=6,RowNumber=2,SeatNumber=10},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=1},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=2},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=3},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=4},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=5},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=6},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=7},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=8},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=9},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=10},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=11},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=12},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=13},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=14},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=15},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=1},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=2},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=3},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=4},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=5},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=6},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=7},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=8},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=9},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=10},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=11},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=12},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=13},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=14},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=15},
            };

            seats.ForEach(s => context.Seats.Add(s));
            context.SaveChanges();
             /*-----------end of table creation------------ */

            /* -----------start of table creation------------ */
            var shows = new List<Show>
            {
            new Show{BeginTime=DateTime.Parse("2018-03-16 16:15:00.000"),EndTime=DateTime.Parse("2018-03-16 18:30:00.000"),MovieID=9,RoomID=2,NumberofTickets=11,ChildDiscount=true,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-16 19:00:00.000"),EndTime=DateTime.Parse("2018-03-16 21:00:00.000"),MovieID=1,RoomID=1,NumberofTickets=10,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-16 19:00:00.000"),EndTime=DateTime.Parse("2018-03-16 21:00:00.000"),MovieID=2,RoomID=2,NumberofTickets=3,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-16 19:08:00.000"),EndTime=DateTime.Parse("2018-03-16 21:08:00.000"),MovieID=3,RoomID=3,NumberofTickets=1,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-16 19:11:00.000"),EndTime=DateTime.Parse("2018-03-16 21:11:00.000"),MovieID=4,RoomID=4,NumberofTickets=3,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-16 19:00:00.000"),EndTime=DateTime.Parse("2018-03-16 21:00:00.000"),MovieID=5,RoomID=5,NumberofTickets=6,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-16 19:00:00.000"),EndTime=DateTime.Parse("2018-03-16 21:00:00.000"),MovieID=6,RoomID=6,NumberofTickets=2,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-16 21:15:00.000"),EndTime=DateTime.Parse("2018-03-16 23:15:00.000"),MovieID=7,RoomID=1,NumberofTickets=10,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-16 21:15:00.000"),EndTime=DateTime.Parse("2018-03-16 22:30:00.000"),MovieID=8,RoomID=2,NumberofTickets=15,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true}
            };

            shows.ForEach(s => context.Shows.Add(s));
            context.SaveChanges();
            /* -----------end of table creation------------ */

            /* -----------start of table creation------------*/
            var tickets = new List<Ticket>
            {
            // Reservation 20180681426908 20180681426909
            new Ticket{Price=9.50M,TicketType="Normaal",IsPaid=false,ShowID=1,SeatID=5,ReservationID=20180681426909,Popcorn=false},
            new Ticket{Price=13.00M,TicketType="Kind",IsPaid=false,ShowID=1,SeatID=6,ReservationID=20180681426909,Popcorn=true},
            new Ticket{Price=13.00M,TicketType="Kind",IsPaid=false,ShowID=1,SeatID=7,ReservationID=20180681426909,Popcorn=true},
            new Ticket{Price=12.00M,TicketType="Normaal",IsPaid=true,ShowID=3,SeatID=11,ReservationID=20180681426908,Popcorn=false},
            new Ticket{Price=12.00M,TicketType="Normaal",IsPaid=true,ShowID=3,SeatID=12,ReservationID=20180681426908,Popcorn=false},
            new Ticket{Price=15.00M,TicketType="Kind",IsPaid=true,ShowID=3,SeatID=13,ReservationID=20180681426908,Popcorn=true},
            new Ticket{Price=10.00M,TicketType="Kind",IsPaid=true,ShowID=3,SeatID=14,ReservationID=20180681426908,Popcorn=false},
            new Ticket{Price=10.50M,TicketType="Senior",IsPaid=true,ShowID=3,SeatID=15,ReservationID=20180681426908,Popcorn=false}
            };

            tickets.ForEach(s => context.Tickets.Add(s));
            context.SaveChanges();
            /*-----------end of table creation------------ */

        }
    }
}
