using Domain.Entities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Hosting;

namespace Domain.Concrete
{
    // DropCreateDatabaseIfModelChanges VS DropCreateDatabaseAlways
    public class CinemaInitializer : System.Data.Entity.DropCreateDatabaseIfModelChanges<EFDbContext>
    {
        byte[] uprising = File.ReadAllBytes(HostingEnvironment.MapPath("~/Content/pacific-rim-uprising.jpg"));
        byte[] hour = File.ReadAllBytes(HostingEnvironment.MapPath("~/Content/darkest-hour.jpg"));
        byte[] wish = File.ReadAllBytes(HostingEnvironment.MapPath("~/Content/death-wish.jpg"));
        byte[] zee = File.ReadAllBytes(HostingEnvironment.MapPath("~/Content/diep-in-de-zee.jpg"));
        byte[] panther = File.ReadAllBytes(HostingEnvironment.MapPath("~/Content/black-panther.jpg"));
        byte[] verzet = File.ReadAllBytes(HostingEnvironment.MapPath("~/Content/bankier-van-het-verzet.jpg"));
        byte[] bob = File.ReadAllBytes(HostingEnvironment.MapPath("~/Content/bob-de-bouwer.jpg"));
        byte[] red = File.ReadAllBytes(HostingEnvironment.MapPath("~/Content/Red-Sparrow.jpg"));
        byte[] water = File.ReadAllBytes(HostingEnvironment.MapPath("~/Content/the-shape-of-water.jpg"));
        byte[] three = File.ReadAllBytes(HostingEnvironment.MapPath("~/Content/three-billboards.jpg"));
        byte[] tomb = File.ReadAllBytes(HostingEnvironment.MapPath("~/Content/tomb-raider.jpg"));
        byte[] pieter = File.ReadAllBytes(HostingEnvironment.MapPath("~/Content/pieter-konijn.jpg"));
        byte[] buurman = File.ReadAllBytes(HostingEnvironment.MapPath("~/Content/buurman-en-buurman.jpg"));

        protected override void Seed(EFDbContext context)
        {
            //    SEQUENCE:
            //
            //    1. location, 
            //    2. movie 
            //    3. roomlayout
            //    4. room 
            //    5. seat 
            //    6. show
            //    7. ticket
            //    8. showseat

            /* -----------start of table creation------------ */
            var locations = new List<Location>
            {
            new Location{Name="Cinema Breda",City="Breda", Rooms=6,TicketPrice=10.00M},
            new Location{Name="Cinema Eindhoven",City="Eindhoven", Rooms=6,TicketPrice=10.00M},
            new Location{Name="Cinema Rotterdam",City="Rotterdam", Rooms=6,TicketPrice=10.00M}
            };

            locations.ForEach(s => context.Locations.Add(s));
            context.SaveChanges();
            /* -----------end of table creation------------ */

            /* -----------start of table creation------------ */
            var movies = new List<Movie>
            {
            new Movie{Name="Darkest Hour",Language="Engels",LanguageSub="Nederlands", Age=16,MovieType=2,Length=120,Is3D=false, Image=hour,Trailer="https://www.youtube.com/embed/LtJ60u7SUSw",MainActors="Gary Oldman, Lily James",SubActors="Kristin Scott Thomas",IMDB="tt4555426",Website="http://www.imdb.com/title/tt4555426/?ref_=plg_rt_1",Director="Joe Wright", LocationID=1,Description="Een geweldige film over iets", Genre="historisch"},
            new Movie{Name="Red Sparrow",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=140,Is3D=false, Image=red,Trailer="https://www.youtube.com/embed/PmUL6wMpMWw",MainActors="Jennifer Lawerence, Joel Edgerton",SubActors="Matthias Schoenaerts",IMDB="tt2873282",Website="http://www.imdb.com/title/tt2873282/?ref_=plg_rt_1",Director="Francis Lawrence", LocationID=1,Description="Een geweldige film over iets", Genre="actie"},
            new Movie{Name="Death Wish",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=108,Is3D=true, Image=wish,Trailer="https://www.youtube.com/embed/HzILu6yyA20",MainActors="Bruce Willis",SubActors="Vincent D'Onofrio, Elisabeth Shue",IMDB="tt1137450",Website="http://www.imdb.com/title/tt1137450/?ref_=plg_rt_1",Director="Eli Roth", LocationID=1,Description="Een geweldige film over iets", Genre="actie"},
            new Movie{Name="Diep in de Zee",Language="Nederlands",LanguageSub="Nederlands",Age=6,MovieType=2,Length=91,Is3D=false, Image=zee,Trailer="https://www.youtube.com/embed/q3__DYiRn_4",MainActors="Justin Felbinger",SubActors=" ",IMDB="tt4105584",Website="http://www.imdb.com/title/tt4105584/?ref_=plg_rt_1",Director="Julio Soto Gurpide", LocationID=1, Description="Een geweldige film over iets", Genre="actie"},
            new Movie{Name="Black Panther",Language="Engels",LanguageSub="Nederlands",Age=12,MovieType=2,Length=134,Is3D=true, Image=panther,Trailer="https://www.youtube.com/embed/xjDjIWPwcPU",MainActors="Chadwick Boseman",SubActors="Michael B. Jordan, Lupita Nyong'o",IMDB="tt1825683",Website="http://www.imdb.com/title/tt1825683/?ref_=plg_rt_1",Director="Ryan Coogler",LocationID=1, Description="Een geweldige film over iets", Genre="actie"},
            new Movie{Name="Bankier van het Verzet",Language="Nederlands",LanguageSub="Nederlands",Age=12,MovieType=2,Length=123,Is3D=false, Image=verzet,Trailer="https://www.youtube.com/embed/eg5El9N03Fs",MainActors="Barry Atsma",SubActors="Jacob Derwig, Pierre Bokma",IMDB="tt4610378",Website="http://www.imdb.com/title/tt4610378/?ref_=plg_rt_1",Director="Joram Lürsen",LocationID=1,Description="Een geweldige film over iets", Genre="actie"},
            new Movie{Name="The Shape of Water",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=123,Is3D=false, Image=water,Trailer="https://www.youtube.com/embed/XFYWazblaUA",MainActors="Sally Hawkins, Octavia Spencer",SubActors="Michael Shannon",IMDB="tt5580390",Website="http://www.imdb.com/title/tt5580390/?ref_=plg_rt_1",Director="Guillermo del Toro",LocationID=1,Description="Een geweldige film over iets", Genre="actie"},
            new Movie{Name="Three BillBoards Outside Ebbing, Missouri",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=115,Is3D=false, Image=three,Trailer="https://www.youtube.com/embed/Jit3YhGx5pU",MainActors="Frances McDormand",SubActors="Woody Harrelson, Sam Rockwell",IMDB="tt5027774",Website="http://www.imdb.com/title/tt5027774/?ref_=plg_rt_1",Director="Martin McDonagh",LocationID=1,Description="Een geweldige film over iets", Genre="actie"},
            new Movie{Name="Buurman en Buurman bouwen een huis",Language="Nederlands",LanguageSub="Nederlands",Age=4,MovieType=2,Length=150,Is3D=false, Image=buurman,Trailer="https://www.youtube.com/embed/fPeTzUYJKxQ",MainActors="Kees Prins, Siem van Leeuwen",SubActors=" ",IMDB="tt8007250",Website="http://www.imdb.com/title/tt8007250/?ref_=plg_rt_1",Director="Marek Benes",LocationID=1,Description="Een geweldige film over iets", Genre="kids"},

            new Movie{Name="Darkest Hour",Language="Engels",LanguageSub="Nederlands", Age=16,MovieType=2,Length=120,Is3D=false, Image=hour,Trailer="https://www.youtube.com/embed/LtJ60u7SUSw",MainActors="Gary Oldman, Lily James",SubActors="Kristin Scott Thomas",IMDB="tt4555426",Website="http://www.imdb.com/title/tt4555426/?ref_=plg_rt_1",Director="Joe Wright",LocationID=2,Description="Een geweldige film over iets", Genre="historisch"},
            new Movie{Name="Tomb Raider",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=140,Is3D=false, Image=tomb,Trailer="https://www.youtube.com/embed/3KkhD0MnaJU",MainActors="Alicia Vikander",SubActors="Dominic West, Walton Goggins",IMDB="tt1365519",Website="http://www.imdb.com/title/tt1365519/?ref_=plg_rt_1",Director="Roar Uthaug",LocationID=2,Description="Een geweldige film over iets", Genre="actie"},
            new Movie{Name="Death Wish",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=108,Is3D=true, Image=wish,Trailer="https://www.youtube.com/embed/HzILu6yyA20",MainActors="Bruce Willis",SubActors="Vincent D'Onofrio, Elisabeth Shue",IMDB="tt1137450",Website="http://www.imdb.com/title/tt1137450/?ref_=plg_rt_1",Director="Eli Roth",LocationID=2,Description="Een geweldige film over iets", Genre="actie"},
            new Movie{Name="Diep in de Zee",Language="Nederlands",LanguageSub="Nederlands",Age=6,MovieType=2,Length=91,Is3D=false, Image=zee,Trailer="https://www.youtube.com/embed/q3__DYiRn_4",MainActors="Justin Felbinger",SubActors=" ",IMDB="tt4105584",Website="http://www.imdb.com/title/tt4105584/?ref_=plg_rt_1",Director="Julio Soto Gurpide",LocationID=2,Description="Een geweldige film over iets", Genre="actie"},
            new Movie{Name="Black Panther",Language="Engels",LanguageSub="Nederlands",Age=12,MovieType=2,Length=134,Is3D=true, Image=panther,Trailer="https://www.youtube.com/embed/xjDjIWPwcPU",MainActors="Chadwick Boseman",SubActors="Michael B. Jordan, Lupita Nyong'o",IMDB="tt1825683",Website="http://www.imdb.com/title/tt1825683/?ref_=plg_rt_1",Director="Ryan Coogler",LocationID=2,Description="Een geweldige film over iets", Genre="actie"},
            new Movie{Name="Bankier van het Verzet",Language="Nederlands",LanguageSub="Nederlands",Age=12,MovieType=2,Length=123,Is3D=false, Image=verzet,Trailer="https://www.youtube.com/embed/eg5El9N03Fs",MainActors="Barry Atsma",SubActors="Jacob Derwig, Pierre Bokma",IMDB="tt4610378",Website="http://www.imdb.com/title/tt4610378/?ref_=plg_rt_1",Director="Joram Lürsen",LocationID=2,Description="Een geweldige film over iets", Genre="historisch"},
            new Movie{Name="The Shape of Water",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=123,Is3D=false, Image=water,Trailer="https://www.youtube.com/embed/XFYWazblaUA",MainActors="Sally Hawkins, Octavia Spencer",SubActors="Michael Shannon",IMDB="tt5580390",Website="http://www.imdb.com/title/tt5580390/?ref_=plg_rt_1",Director="Guillermo del Toro",LocationID=2,Description="Een geweldige film over iets", Genre="fantasie"},
            new Movie{Name="Three BillBoards Outside Ebbing, Missouri",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=115,Is3D=false, Image=three,Trailer="https://www.youtube.com/embed/Jit3YhGx5pU",MainActors="Frances McDormand",SubActors="Woody Harrelson, Sam Rockwell",IMDB="tt5027774",Website="http://www.imdb.com/title/tt5027774/?ref_=plg_rt_1",Director="Martin McDonagh",LocationID=2,Description="Een geweldige film over iets",Genre="actie"},
            new Movie{Name="Pieter Konijn",Language="Nederlands",LanguageSub="Nederlands",Age=4,MovieType=2,Length=150,Is3D=false, Image=pieter,Trailer="https://www.youtube.com/embed/RDw8zHTQTzk",MainActors=" ",SubActors=" ",IMDB="tt5117670",Website="http://www.imdb.com/title/tt5117670/?ref_=plg_rt_1",Director="Will Gluck",LocationID=2, Genre="kids" },

            new Movie{Name="Darkest Hour",Language="Engels",LanguageSub="Nederlands", Age=16,MovieType=2,Length=120,Is3D=false, Image=hour,Trailer="https://www.youtube.com/embed/LtJ60u7SUSw",MainActors="Gary Oldman, Lily James",SubActors="Kristin Scott Thomas",IMDB="tt4555426",Website="http://www.imdb.com/title/tt4555426/?ref_=plg_rt_1",Director="Joe Wright",LocationID=3,Description="Een geweldige film over iets", Genre="historisch"},
            new Movie{Name="Red Sparrow",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=140,Is3D=false, Image=red,Trailer="https://www.youtube.com/embed/PmUL6wMpMWw",MainActors="Jennifer Lawerence, Joel Edgerton",SubActors="Matthias Schoenaerts",IMDB="tt2873282",Website="http://www.imdb.com/title/tt2873282/?ref_=plg_rt_1",Director="Francis Lawrence",LocationID=3,Description="Een geweldige film over iets", Genre="actie"},
            new Movie{Name="Pacific Rim Uprising",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=108,Is3D=true, Image=uprising,Trailer="https://www.youtube.com/embed/8BAhwgjMvnM",MainActors="John Boyega, Scott Eastwood",SubActors="Cailee Spaeny",IMDB="tt2557478",Website="http://www.imdb.com/title/tt2557478/?ref_=plg_rt_1",Director="Steven S. DeKnight",LocationID=3,Description="Een geweldige film over iets", Genre="actie"},
            new Movie{Name="Diep in de Zee",Language="Nederlands",LanguageSub="Nederlands",Age=6,MovieType=2,Length=91,Is3D=false, Image=zee,Trailer="https://www.youtube.com/embed/q3__DYiRn_4",MainActors="Justin Felbinger",SubActors=" ",IMDB="tt4105584",Website="http://www.imdb.com/title/tt4105584/?ref_=plg_rt_1",Director="Julio Soto Gurpide",LocationID=3,Description="Een geweldige film over iets", Genre="actie"},
            new Movie{Name="Black Panther",Language="Engels",LanguageSub="Nederlands",Age=12,MovieType=2,Length=134,Is3D=true, Image=panther,Trailer="https://www.youtube.com/embed/xjDjIWPwcPU",MainActors="Chadwick Boseman",SubActors="Michael B. Jordan, Lupita Nyong'o",IMDB="tt1825683",Website="http://www.imdb.com/title/tt1825683/?ref_=plg_rt_1",Director="Ryan Coogler",LocationID=3,Description="Een geweldige film over iets", Genre="actie"},
            new Movie{Name="Bankier van het Verzet",Language="Nederlands",LanguageSub="Nederlands",Age=12,MovieType=2,Length=123,Is3D=false, Image=verzet,Trailer="https://www.youtube.com/embed/eg5El9N03Fs",MainActors="Barry Atsma",SubActors="Jacob Derwig, Pierre Bokma",IMDB="tt4610378",Website="http://www.imdb.com/title/tt4610378/?ref_=plg_rt_1",Director="Joram Lürsen",LocationID=3,Description="Een geweldige film over iets", Genre="historisch"},
            new Movie{Name="The Shape of Water",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=123,Is3D=false, Image=water,Trailer="https://www.youtube.com/embed/XFYWazblaUA",MainActors="Sally Hawkins, Octavia Spencer",SubActors="Michael Shannon",IMDB="tt5580390",Website="http://www.imdb.com/title/tt5580390/",Director="Guillermo del Toro",LocationID=3,Description="Een geweldige film over iets", Genre="fantasie"},
            new Movie{Name="Three BillBoards Outside Ebbing, Missouri",Language="Engels",LanguageSub="Nederlands",Age=16,MovieType=2,Length=115,Is3D=false, Image=three,Trailer="https://www.youtube.com/embed/Jit3YhGx5pU",MainActors="Frances McDormand",SubActors="Woody Harrelson, Sam Rockwell",IMDB="tt5027774",Website="http://www.imdb.com/title/tt5027774/?ref_=plg_rt_1",Director="Martin McDonagh",LocationID=3,Description="Een geweldige film over iets", Genre="actie"},
            new Movie{Name="Bob de Bouwer - Mega Machines",Language="Nederlands",LanguageSub="Nederlands",Age=4,MovieType=2,Length=150,Is3D=false, Image=bob,Trailer="https://www.youtube.com/embed/dliLdfnNn78",MainActors="Daniel Bacon",SubActors="Ryan Beil, Ian James Corlett",IMDB="tt6604334",Website="http://www.imdb.com/title/tt6604334/?ref_=plg_rt_1",Director="Colleen Morton",LocationID=3,Description="Een geweldige film over iets", Genre="kids"}

            };

            movies.ForEach(s => context.Movies.Add(s));
            context.SaveChanges();
            /* -----------end of table creation------------ */

            /* -----------start of table creation------------ */
            var rooms = new List<Room>
            {
            new Room{RoomID=1,RoomNumber=1,TotalSeats=240,RowCount=12},
            new Room{RoomID=2,RoomNumber=2,TotalSeats=240,RowCount=12},
            new Room{RoomID=3,RoomNumber=3,TotalSeats=240,RowCount=12},
            new Room{RoomID=4,RoomNumber=4,TotalSeats=77,RowCount=7},
            new Room{RoomID=5,RoomNumber=5,TotalSeats=50,RowCount=4},
            new Room{RoomID=6,RoomNumber=6,TotalSeats=50,RowCount=4}
            };

            rooms.ForEach(s => context.Rooms.Add(s));
            context.SaveChanges();
            /* -----------end of table creation------------ */

            /* -----------start of table creation------------*/
            var seats = new List<Seat>
            {
            new Seat{RoomID=1,RowNumber=1,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=1,SeatNumber=20},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=2,SeatNumber=20},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=3,SeatNumber=20},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=4,SeatNumber=20},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=5,SeatNumber=20},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=6,SeatNumber=20},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=7,SeatNumber=20},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=8,SeatNumber=20},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=9,SeatNumber=20},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=10,SeatNumber=20},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=11,SeatNumber=20},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=1},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=2},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=3},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=4},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=5},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=6},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=7},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=8},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=9},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=10},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=11},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=12},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=13},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=14},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=15},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=16},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=17},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=18},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=19},
            new Seat{RoomID=1,RowNumber=12,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=1,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=2,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=3,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=4,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=5,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=6,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=7,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=8,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=9,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=10,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=11,SeatNumber=20},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=1},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=2},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=3},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=4},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=5},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=6},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=7},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=8},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=9},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=10},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=11},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=12},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=13},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=14},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=15},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=16},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=17},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=18},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=19},
            new Seat{RoomID=2,RowNumber=12,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=1,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=2,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=3,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=4,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=5,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=6,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=7,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=8,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=9,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=10,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=11,SeatNumber=20},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=1},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=2},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=3},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=4},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=5},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=6},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=7},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=8},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=9},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=10},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=11},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=12},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=13},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=14},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=15},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=16},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=17},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=18},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=19},
            new Seat{RoomID=3,RowNumber=12,SeatNumber=20},
            new Seat{RoomID=4,RowNumber=1,SeatNumber=1},
            new Seat{RoomID=4,RowNumber=1,SeatNumber=2},
            new Seat{RoomID=4,RowNumber=1,SeatNumber=3},
            new Seat{RoomID=4,RowNumber=1,SeatNumber=4},
            new Seat{RoomID=4,RowNumber=1,SeatNumber=5},
            new Seat{RoomID=4,RowNumber=1,SeatNumber=6},
            new Seat{RoomID=4,RowNumber=2,SeatNumber=1},
            new Seat{RoomID=4,RowNumber=2,SeatNumber=2},
            new Seat{RoomID=4,RowNumber=2,SeatNumber=3},
            new Seat{RoomID=4,RowNumber=2,SeatNumber=4},
            new Seat{RoomID=4,RowNumber=2,SeatNumber=5},
            new Seat{RoomID=4,RowNumber=2,SeatNumber=6},
            new Seat{RoomID=4,RowNumber=3,SeatNumber=1},
            new Seat{RoomID=4,RowNumber=3,SeatNumber=2},
            new Seat{RoomID=4,RowNumber=3,SeatNumber=3},
            new Seat{RoomID=4,RowNumber=3,SeatNumber=4},
            new Seat{RoomID=4,RowNumber=3,SeatNumber=5},
            new Seat{RoomID=4,RowNumber=3,SeatNumber=6},
            new Seat{RoomID=4,RowNumber=4,SeatNumber=1},
            new Seat{RoomID=4,RowNumber=4,SeatNumber=2},
            new Seat{RoomID=4,RowNumber=4,SeatNumber=3},
            new Seat{RoomID=4,RowNumber=4,SeatNumber=4},
            new Seat{RoomID=4,RowNumber=4,SeatNumber=5},
            new Seat{RoomID=4,RowNumber=4,SeatNumber=6},
            new Seat{RoomID=4,RowNumber=5,SeatNumber=1},
            new Seat{RoomID=4,RowNumber=5,SeatNumber=2},
            new Seat{RoomID=4,RowNumber=5,SeatNumber=3},
            new Seat{RoomID=4,RowNumber=5,SeatNumber=4},
            new Seat{RoomID=4,RowNumber=5,SeatNumber=5},
            new Seat{RoomID=4,RowNumber=5,SeatNumber=6},
            new Seat{RoomID=4,RowNumber=6,SeatNumber=1},
            new Seat{RoomID=4,RowNumber=6,SeatNumber=2},
            new Seat{RoomID=4,RowNumber=6,SeatNumber=3},
            new Seat{RoomID=4,RowNumber=6,SeatNumber=4},
            new Seat{RoomID=4,RowNumber=6,SeatNumber=5},
            new Seat{RoomID=4,RowNumber=6,SeatNumber=6},
            new Seat{RoomID=4,RowNumber=7,SeatNumber=1},
            new Seat{RoomID=4,RowNumber=7,SeatNumber=2},
            new Seat{RoomID=4,RowNumber=7,SeatNumber=3},
            new Seat{RoomID=4,RowNumber=7,SeatNumber=4},
            new Seat{RoomID=4,RowNumber=7,SeatNumber=5},
            new Seat{RoomID=4,RowNumber=7,SeatNumber=6},
            new Seat{RoomID=4,RowNumber=1,SeatNumber=7},
            new Seat{RoomID=4,RowNumber=1,SeatNumber=8},
            new Seat{RoomID=4,RowNumber=1,SeatNumber=9},
            new Seat{RoomID=4,RowNumber=1,SeatNumber=10},
            new Seat{RoomID=4,RowNumber=1,SeatNumber=11},
            new Seat{RoomID=4,RowNumber=2,SeatNumber=7},
            new Seat{RoomID=4,RowNumber=2,SeatNumber=8},
            new Seat{RoomID=4,RowNumber=2,SeatNumber=9},
            new Seat{RoomID=4,RowNumber=2,SeatNumber=10},
            new Seat{RoomID=4,RowNumber=2,SeatNumber=11},
            new Seat{RoomID=4,RowNumber=3,SeatNumber=7},
            new Seat{RoomID=4,RowNumber=3,SeatNumber=8},
            new Seat{RoomID=4,RowNumber=3,SeatNumber=9},
            new Seat{RoomID=4,RowNumber=3,SeatNumber=10},
            new Seat{RoomID=4,RowNumber=3,SeatNumber=11},
            new Seat{RoomID=4,RowNumber=4,SeatNumber=7},
            new Seat{RoomID=4,RowNumber=4,SeatNumber=8},
            new Seat{RoomID=4,RowNumber=4,SeatNumber=9},
            new Seat{RoomID=4,RowNumber=4,SeatNumber=10},
            new Seat{RoomID=4,RowNumber=4,SeatNumber=11},
            new Seat{RoomID=4,RowNumber=5,SeatNumber=7},
            new Seat{RoomID=4,RowNumber=5,SeatNumber=8},
            new Seat{RoomID=4,RowNumber=5,SeatNumber=9},
            new Seat{RoomID=4,RowNumber=5,SeatNumber=10},
            new Seat{RoomID=4,RowNumber=5,SeatNumber=11},
            new Seat{RoomID=4,RowNumber=6,SeatNumber=7},
            new Seat{RoomID=4,RowNumber=6,SeatNumber=8},
            new Seat{RoomID=4,RowNumber=6,SeatNumber=9},
            new Seat{RoomID=4,RowNumber=6,SeatNumber=10},
            new Seat{RoomID=4,RowNumber=6,SeatNumber=11},
            new Seat{RoomID=4,RowNumber=7,SeatNumber=7},
            new Seat{RoomID=4,RowNumber=7,SeatNumber=8},
            new Seat{RoomID=4,RowNumber=7,SeatNumber=9},
            new Seat{RoomID=4,RowNumber=7,SeatNumber=10},
            new Seat{RoomID=4,RowNumber=7,SeatNumber=11},
            new Seat{RoomID=5,RowNumber=1,SeatNumber=1},
            new Seat{RoomID=5,RowNumber=1,SeatNumber=2},
            new Seat{RoomID=5,RowNumber=1,SeatNumber=3},
            new Seat{RoomID=5,RowNumber=1,SeatNumber=4},
            new Seat{RoomID=5,RowNumber=1,SeatNumber=5},
            new Seat{RoomID=5,RowNumber=1,SeatNumber=6},
            new Seat{RoomID=5,RowNumber=1,SeatNumber=7},
            new Seat{RoomID=5,RowNumber=1,SeatNumber=8},
            new Seat{RoomID=5,RowNumber=1,SeatNumber=9},
            new Seat{RoomID=5,RowNumber=1,SeatNumber=10},
            new Seat{RoomID=5,RowNumber=2,SeatNumber=1},
            new Seat{RoomID=5,RowNumber=2,SeatNumber=2},
            new Seat{RoomID=5,RowNumber=2,SeatNumber=3},
            new Seat{RoomID=5,RowNumber=2,SeatNumber=4},
            new Seat{RoomID=5,RowNumber=2,SeatNumber=5},
            new Seat{RoomID=5,RowNumber=2,SeatNumber=6},
            new Seat{RoomID=5,RowNumber=2,SeatNumber=7},
            new Seat{RoomID=5,RowNumber=2,SeatNumber=8},
            new Seat{RoomID=5,RowNumber=2,SeatNumber=9},
            new Seat{RoomID=5,RowNumber=2,SeatNumber=10},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=1},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=2},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=3},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=4},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=5},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=6},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=7},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=8},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=9},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=10},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=11},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=12},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=13},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=14},
            new Seat{RoomID=5,RowNumber=3,SeatNumber=15},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=1},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=2},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=3},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=4},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=5},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=6},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=7},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=8},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=9},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=10},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=11},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=12},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=13},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=14},
            new Seat{RoomID=5,RowNumber=4,SeatNumber=15},
            new Seat{RoomID=6,RowNumber=1,SeatNumber=1},
            new Seat{RoomID=6,RowNumber=1,SeatNumber=2},
            new Seat{RoomID=6,RowNumber=1,SeatNumber=3},
            new Seat{RoomID=6,RowNumber=1,SeatNumber=4},
            new Seat{RoomID=6,RowNumber=1,SeatNumber=5},
            new Seat{RoomID=6,RowNumber=1,SeatNumber=6},
            new Seat{RoomID=6,RowNumber=1,SeatNumber=7},
            new Seat{RoomID=6,RowNumber=1,SeatNumber=8},
            new Seat{RoomID=6,RowNumber=1,SeatNumber=9},
            new Seat{RoomID=6,RowNumber=1,SeatNumber=10},
            new Seat{RoomID=6,RowNumber=2,SeatNumber=1},
            new Seat{RoomID=6,RowNumber=2,SeatNumber=2},
            new Seat{RoomID=6,RowNumber=2,SeatNumber=3},
            new Seat{RoomID=6,RowNumber=2,SeatNumber=4},
            new Seat{RoomID=6,RowNumber=2,SeatNumber=5},
            new Seat{RoomID=6,RowNumber=2,SeatNumber=6},
            new Seat{RoomID=6,RowNumber=2,SeatNumber=7},
            new Seat{RoomID=6,RowNumber=2,SeatNumber=8},
            new Seat{RoomID=6,RowNumber=2,SeatNumber=9},
            new Seat{RoomID=6,RowNumber=2,SeatNumber=10},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=1},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=2},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=3},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=4},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=5},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=6},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=7},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=8},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=9},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=10},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=11},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=12},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=13},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=14},
            new Seat{RoomID=6,RowNumber=3,SeatNumber=15},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=1},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=2},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=3},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=4},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=5},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=6},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=7},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=8},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=9},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=10},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=11},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=12},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=13},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=14},
            new Seat{RoomID=6,RowNumber=4,SeatNumber=15},
            };

            seats.ForEach(s => context.Seats.Add(s));
            context.SaveChanges();
            /*-----------end of table creation------------ */

            /* -----------start of table creation------------ */
            var shows = new List<Show>
            {
            new Show{BeginTime=DateTime.Parse("2018-03-26 16:15:00.000"),EndTime=DateTime.Parse("2018-03-26 18:30:00.000"),MovieID=9,RoomID=2,NumberofTickets=11,ChildDiscount=true,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 19:00:00.000"),EndTime=DateTime.Parse("2018-03-26 21:00:00.000"),MovieID=1,RoomID=1,NumberofTickets=10,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 19:00:00.000"),EndTime=DateTime.Parse("2018-03-26 21:00:00.000"),MovieID=2,RoomID=2,NumberofTickets=3,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 19:08:00.000"),EndTime=DateTime.Parse("2018-03-26 21:08:00.000"),MovieID=3,RoomID=3,NumberofTickets=1,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 19:11:00.000"),EndTime=DateTime.Parse("2018-03-26 21:11:00.000"),MovieID=4,RoomID=4,NumberofTickets=3,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 19:00:00.000"),EndTime=DateTime.Parse("2018-03-26 21:00:00.000"),MovieID=5,RoomID=5,NumberofTickets=6,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 19:00:00.000"),EndTime=DateTime.Parse("2018-03-26 21:00:00.000"),MovieID=6,RoomID=6,NumberofTickets=2,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 21:15:00.000"),EndTime=DateTime.Parse("2018-03-26 23:15:00.000"),MovieID=7,RoomID=1,NumberofTickets=10,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 21:15:00.000"),EndTime=DateTime.Parse("2018-03-26 22:30:00.000"),MovieID=8,RoomID=2,NumberofTickets=15,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},

            new Show{BeginTime=DateTime.Parse("2018-03-26 16:15:00.000"),EndTime=DateTime.Parse("2018-03-26 18:30:00.000"),MovieID=19,RoomID=2,NumberofTickets=11,ChildDiscount=true,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 19:00:00.000"),EndTime=DateTime.Parse("2018-03-26 21:00:00.000"),MovieID=21,RoomID=1,NumberofTickets=10,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 19:00:00.000"),EndTime=DateTime.Parse("2018-03-26 21:00:00.000"),MovieID=22,RoomID=2,NumberofTickets=3,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 19:08:00.000"),EndTime=DateTime.Parse("2018-03-26 21:08:00.000"),MovieID=23,RoomID=3,NumberofTickets=1,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 19:11:00.000"),EndTime=DateTime.Parse("2018-03-26 21:11:00.000"),MovieID=24,RoomID=4,NumberofTickets=3,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 19:00:00.000"),EndTime=DateTime.Parse("2018-03-26 21:00:00.000"),MovieID=25,RoomID=5,NumberofTickets=6,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 19:00:00.000"),EndTime=DateTime.Parse("2018-03-26 21:00:00.000"),MovieID=26,RoomID=6,NumberofTickets=2,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 21:15:00.000"),EndTime=DateTime.Parse("2018-03-26 23:15:00.000"),MovieID=27,RoomID=1,NumberofTickets=10,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},

            new Show{BeginTime=DateTime.Parse("2018-03-26 16:15:00.000"),EndTime=DateTime.Parse("2018-03-26 18:30:00.000"),MovieID=10,RoomID=2,NumberofTickets=11,ChildDiscount=true,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 19:00:00.000"),EndTime=DateTime.Parse("2018-03-26 21:00:00.000"),MovieID=11,RoomID=1,NumberofTickets=10,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 19:00:00.000"),EndTime=DateTime.Parse("2018-03-26 21:00:00.000"),MovieID=12,RoomID=2,NumberofTickets=3,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 19:08:00.000"),EndTime=DateTime.Parse("2018-03-26 21:08:00.000"),MovieID=13,RoomID=3,NumberofTickets=1,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 19:11:00.000"),EndTime=DateTime.Parse("2018-03-26 21:11:00.000"),MovieID=14,RoomID=4,NumberofTickets=3,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 19:00:00.000"),EndTime=DateTime.Parse("2018-03-26 21:00:00.000"),MovieID=15,RoomID=5,NumberofTickets=6,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 19:00:00.000"),EndTime=DateTime.Parse("2018-03-26 21:00:00.000"),MovieID=16,RoomID=6,NumberofTickets=2,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 21:15:00.000"),EndTime=DateTime.Parse("2018-03-26 23:15:00.000"),MovieID=17,RoomID=1,NumberofTickets=10,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true},
            new Show{BeginTime=DateTime.Parse("2018-03-26 21:15:00.000"),EndTime=DateTime.Parse("2018-03-26 22:30:00.000"),MovieID=18,RoomID=2,NumberofTickets=15,ChildDiscount=false,StudentDiscount=true,SeniorDiscount=true}
            };

            shows.ForEach(s => context.Shows.Add(s));
            context.SaveChanges();
            /* -----------end of table creation------------ */

            /* -----------start of table creation------------*/
            var tickets = new List<Ticket>
            {
            // Reservation 20180681426908 20180681426909
            new Ticket{Price=9.50M,TicketType="Normaal",IsPaid=false,ShowID=1,SeatNumber=1,RowNumber=1,ReservationID=20180681426909,Popcorn=false},
            new Ticket{Price=13.00M,TicketType="Kind",IsPaid=false,ShowID=1,SeatNumber=2,RowNumber=1,ReservationID=20180681426909,Popcorn=true},
            new Ticket{Price=13.00M,TicketType="Kind",IsPaid=false,ShowID=1,SeatNumber=3,RowNumber=1,ReservationID=20180681426909,Popcorn=true},
            new Ticket{Price=12.00M,TicketType="Normaal",IsPaid=true,ShowID=3,SeatNumber=1,RowNumber=1,ReservationID=20180681426908,Popcorn=false},
            new Ticket{Price=12.00M,TicketType="Normaal",IsPaid=true,ShowID=3,SeatNumber=2,RowNumber=1,ReservationID=20180681426908,Popcorn=false},
            new Ticket{Price=15.00M,TicketType="Kind",IsPaid=true,ShowID=3,SeatNumber=3,RowNumber=1,ReservationID=20180681426908,Popcorn=true},
            new Ticket{Price=10.00M,TicketType="Kind",IsPaid=true,ShowID=3,SeatNumber=4,RowNumber=1,ReservationID=20180681426908,Popcorn=false},
            new Ticket{Price=10.50M,TicketType="Senior",IsPaid=true,ShowID=3,SeatNumber=5,RowNumber=1,ReservationID=20180681426908,Popcorn=false},
            };

            tickets.ForEach(s => context.Tickets.Add(s));
            context.SaveChanges();
            /*-----------end of table creation------------ */

            /* -----------start of table creation------------*/
            // SHOWSEATS
            var showSeats = new List<ShowSeat>();
            foreach (var i in shows)
            {
                foreach (var j in seats)
                {
                    if (i.RoomID == j.RoomID)
                    {
                        ShowSeat showSeat = new ShowSeat();
                        showSeat.ShowID = i.ShowID;
                        showSeat.RoomID = i.RoomID;
                        showSeat.RowNumber = j.RowNumber;
                        showSeat.SeatNumber = j.SeatNumber;
                        showSeat.IsTaken = false;
                        showSeat.IsReserved = false;
                        showSeats.Add(showSeat);
                    }
                }
            }
            showSeats.ForEach(s => context.ShowSeats.Add(s));
            context.SaveChanges();

            /*-----------end of table creation------------ */

        }
    }
}
